DROP TABLE IF EXISTS issues;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS users;

CREATE TABLE projects (
  project_id INT NOT NULL AUTO_INCREMENT,
  project_name VARCHAR(35) NOT NULL,
  creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_changed TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (project_id)
);

CREATE TABLE issues (
  issue_id INT NOT NULL AUTO_INCREMENT,
  issue_title VARCHAR(50) NOT NULL,
  issue_description VARCHAR(300) NOT NULL DEFAULT "",
  creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_changed TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  project INT NOT NULL,

  PRIMARY KEY (issue_id),
  FOREIGN KEY project_fk (project) REFERENCES projects (project_id) ON DELETE CASCADE
);

CREATE TABLE users (
  user_id INT NOT NULL AUTO_INCREMENT,
  forename VARCHAR(15) DEFAULT NULL,
  surname VARCHAR(20) DEFAULT NULL,
  user_email VARCHAR(30) NOT NULL,
  user_password VARCHAR(20) NOT NULL,
  user_role TINYINT DEFAULT 1 NOT NULL,

  PRIMARY KEY (user_id),
  UNIQUE INDEX (user_email)
);
